#travis configuration for testing
language: minimal

services:
- docker

before_script:
- docker pull ragumanjegowda/docker:latest
- docker run --name "ragu" -dit -u $(id -u) -v ${PWD}:/mnt ragumanjegowda/docker:latest /bin/bash 

jobs:
  include:
    - stage: build 
      script:
      - echo ${PWD}
      - docker exec ragu /mnt/travis.sh 

after_script:
      - docker stop ragu
      - docker rm ragu
