.PHONY: all clean install

all: $(SUBDIRS)
	for subdir in $(SUBDIRS) ; do \
		make -C $$subdir all || exit 1; \
	done

clean: $(SUBDIRS)
	for subdir in $(SUBDIRS) ; do \
		make -C $$subdir clean ; \
		rm -rf .DS_Store *.o *.so *.a; \
	done

install: $(SUBDIRS)
	for subdir in $(SUBDIRS) ; do \
		make -C $$subdir install || exit 1; \
	done
