CC = gcc

# Pass gdb debug flag from command line
# Usage `make D=-g`
CC += $(D)

CFLAGS += -m32 -nostdlib -nostdinc -fno-builtin -fno-stack-protector \
				 -nostartfiles -nodefaultlibs -Wall -Wextra -Werror

AS = nasm
ASFLAGS = -f elf

C_SOURCES += $(wildcard *.c)
S_SOURCES += $(wildcard *.s)
C_OBJECTS += $(C_SOURCES:.c=.o)
S_OBJECTS += $(S_SOURCES:.s=.o)

LDFLAGS += \
	-L$(LIB_DIR) \

INCLUDE += \
