.PHONY: all clean install

all: $(SUBDIRS)
	for subdir in $(SUBDIRS) ; do \
		make -C $$subdir all || exit 1; \
	done

clean: $(SUBDIRS) rmBuild
	for subdir in $(SUBDIRS) ; do \
		make -C $$subdir clean ; \
		rm -rf .DS_Store ; \
	done

install: $(SUBDIRS)
	for subdir in $(SUBDIRS) ; do \
		make -C $$subdir install || exit 1; \
	done

rmBuild:
	rm -rf build iso/boot/kernel.elf bochsrc.txt bochslog.txt vivitsa.iso os.iso \
					.DS_Store com1.out
